### ISSUE TITLE
As a user, the text area should not be editable

### ISSUE THREAD

**Issue by dattupatel** [Shivani2224/Tic-Tac-Toe#2]
Currently, I can type anything in the textarea, and then it never changes when game changes.

Actual:
![CPT2406010018-1792x870](https://github.com/Shivani2224/Tic-Tac-Toe/assets/6920655/7c832040-baf3-448f-a8fc-d3b417582c44)

Expected:
- A user should not be able to type anything in that textarea.

**Comment by Shivani2224** [comment]
Done text area disabled.
