### ISSUE TITLE
As a user, I should be able to play a new full game after i reset

### ISSUE THREAD

**Issue by dattupatel** [Shivani2224/Tic-Tac-Toe#4]
After I press reset, I can click on the tiles only a few times (2 or 3 times at most).  Then, the game becomes unplayable.

**Comment by Shivani2224** [comment]
I have corrected  this

**Comment by dattupatel** [comment]
On reset, reset the `X` and `O` as well.

**Comment by Shivani2224** [comment]
I have added " let " in front of turnO = true in reset function removed it, is it correct?
